name: Add SPARQL query example
description: Form to submit a SPARQL query example
title: "Add example"
labels: ["add-example"]

body:
  - type: textarea
    id: sparql_query
    attributes:
      label: SPARQL query
      description: Provide a working SPARQL query example that reflects what is described in English above
      placeholder: "Add a working SPARQL query"
    validations:
      required: true

  - type: textarea
    id: natural_language_query
    attributes:
      label: Query description
      description: Describe in natural language what the query does. What are you trying to achieve with it? You can use HTML formatting (do not use markdown here).
      placeholder: "Describe your query here"
    validations:
      required: true

  - type: input
    id: filepath
    attributes:
      label: Query file path
      description: Provide the desired file path for your query within the repository examples folder.
      placeholder: "UniProt/001.ttl"
    validations:
      required: true

  - type: checkboxes
    id: predefined_sparql_endpoints
    attributes:
      label: Select the target SPARQL endpoint(s)
      description: Choose one or more SPARQL endpoints from the list, or select 'Other' to provide your own.
      options:
        - label: "https://query.wikidata.org/sparql"
        - label: "https://commons-query.wikimedia.org"
        - label: "https://dbpedia.org/sparql"
        - label: "https://sparql.uniprot.org/sparql"
        - label: "https://sparql.wikipathways.org"

  - type: textarea
    id: custom_sparql_endpoint
    attributes:
      label: Custom SPARQL Endpoints
      description: Please provide the SPARQL endpoints URL here (one per line).
      # placeholder: "https://example.org/sparql"

  - type: textarea
    id: keywords
    attributes:
      label: Keywords
      description: List keywords relevant to the query (one per line).

  # - type: input
  #   id: query_results_link
  #   attributes:
  #     label: Optional link to query results
  #     description: Add a link to the query results (optional).
  #     placeholder: "URL to the query results"
